# Generated by Django 5.1.6 on 2025-04-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="researcher_form",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_Name", models.CharField(max_length=100)),
                ("last_Name", models.CharField(max_length=100)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="profile_pics/"),
                ),
                ("current_project", models.CharField(max_length=100)),
                ("uv_name", models.CharField(max_length=100)),
                ("dept_name", models.CharField(max_length=100)),
                ("session", models.CharField(max_length=100)),
                ("interested_domain", models.CharField(max_length=200)),
                ("experiences", models.CharField(max_length=200)),
                ("Ranking", models.IntegerField(default=60)),
                ("linekdin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("personal_website", models.URLField(blank=True)),
                ("google_scholar_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="researcher_recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Details", models.CharField(max_length=300)),
                (
                    "researcher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Researchers.researcher_form",
                    ),
                ),
            ],
        ),
    ]
