# Generated by Django 5.1.6 on 2025-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_Name", models.CharField(max_length=100)),
                ("last_Name", models.CharField(max_length=100)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="team_members_pics/"),
                ),
                ("current_job", models.CharField(max_length=100)),
                ("work_experience", models.CharField(max_length=100)),
                ("Role", models.CharField(max_length=100)),
                ("uv_name", models.CharField(max_length=100)),
                ("dept_name", models.CharField(max_length=100)),
                ("domain_expertise", models.CharField(max_length=100)),
                ("linekdin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("personal_website", models.URLField(blank=True)),
                ("google_scholar_url", models.URLField(blank=True)),
            ],
        ),
    ]
